### ISSUE TITLE
Player is still alive when he isnt

### ISSUE THREAD

**Issue by C41nn** [Tater-Certified/LifeSteal#3]
When testing and trying to revive a friend he is banned and i can't revive him. It says "player is still alive".

**Comment by QPCrummer** [comment]
Hello, thanks for reporting this. I think the only true fix to this issue is to rewrite the code that deals with checking offline player’s NBT data. Either I need to refine the existing system, or make an improved system that doesn’t require loading NBT data. I’m a bit busy currently, but I will most likely be able to push some fix in a few days. 
Again, thank you for creating this issue. It is very hard to test this mod with actual players in the dev environment, so I really appreciate when others can test with real players

**Comment by QPCrummer** [comment]
This should be fixed in the latest version 1.4.0
